version: '3.3'

services:
  backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      - POSTGRES_USER=vshtefan
      - POSTGRES_PASSWORD=Tpc*3SYUgWL.CKr
      - POSTGRES_DB=movies_pg
  db:
    image: postgres
    environment:
      - POSTGRES_USER=vshtefan
      - POSTGRES_PASSWORD=Tpc*3SYUgWL.CKr
      - POSTGRES_DB=movies_pg